mysql:
  host: "pc-bp18rn0tqu85a1600-public.rwlb.rds.aliyuncs.com"
  port: 3306
  username: "lab_426293230"
  password: "07577c220351_#@Aa"
  dbname: "polardb_mysql_16659mqo"

redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: ""

mongo:
  uri: "dasda"
  db: "asd"